name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch Google API index
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      run: |
        export PYTHONUNBUFFERED=True
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        python main.py
        git add .
        git commit -m "Update report"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
